"""replace_enums_with_dict_tables

Revision ID: 177e9728e1fe
Revises: e7be960496a5
Create Date: 2025-09-16 01:13:16.360592+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "177e9728e1fe"
down_revision: Union[str, None] = "e7be960496a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
