"""add_dictionary_table_foreign_keys

Revision ID: 1a837ec36ac7
Revises: 177e9728e1fe
Create Date: 2025-09-16 01:39:28.694112+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a837ec36ac7'
down_revision: Union[str, None] = '177e9728e1fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add status_id to tournaments table
    op.add_column('tournaments', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('tournament_type_id', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('format_id', sa.Integer(), nullable=True))
    
    # Add foreign key constraints for tournaments
    op.create_foreign_key('fk_tournaments_status_id', 'tournaments', 'dict_tournament_statuses', ['status_id'], ['id'])
    op.create_foreign_key('fk_tournaments_tournament_type_id', 'tournaments', 'dict_tournament_types', ['tournament_type_id'], ['id'])
    op.create_foreign_key('fk_tournaments_format_id', 'tournaments', 'dict_tournament_formats', ['format_id'], ['id'])
    
    # Add status_id to tournament_registrations table
    op.add_column('tournament_registrations', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tournament_registrations_status_id', 'tournament_registrations', 'dict_registration_statuses', ['status_id'], ['id'])
    
    # Add status_id to tournament_matches table
    op.add_column('tournament_matches', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tournament_matches_status_id', 'tournament_matches', 'dict_match_statuses', ['status_id'], ['id'])
    
    # Add status_id to match_check_ins table
    op.add_column('match_check_ins', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_match_check_ins_status_id', 'match_check_ins', 'dict_checkin_statuses', ['status_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove foreign key constraints and columns in reverse order
    op.drop_constraint('fk_match_check_ins_status_id', 'match_check_ins', type_='foreignkey')
    op.drop_column('match_check_ins', 'status_id')
    
    op.drop_constraint('fk_tournament_matches_status_id', 'tournament_matches', type_='foreignkey')
    op.drop_column('tournament_matches', 'status_id')
    
    op.drop_constraint('fk_tournament_registrations_status_id', 'tournament_registrations', type_='foreignkey')
    op.drop_column('tournament_registrations', 'status_id')
    
    op.drop_constraint('fk_tournaments_format_id', 'tournaments', type_='foreignkey')
    op.drop_constraint('fk_tournaments_tournament_type_id', 'tournaments', type_='foreignkey')
    op.drop_constraint('fk_tournaments_status_id', 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'format_id')
    op.drop_column('tournaments', 'tournament_type_id')
    op.drop_column('tournaments', 'status_id')
    
    # ### end Alembic commands ###
