"""add_champions_table

Revision ID: 78011c530eba
Revises: 1a837ec36ac7
Create Date: 2025-09-16 06:47:21.211341+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78011c530eba"
down_revision: Union[str, None] = "1a837ec36ac7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'champions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('champion_id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('lore', sa.Text(), nullable=True),
        sa.Column('blurb', sa.Text(), nullable=True),
        sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('partype', sa.String(length=50), nullable=True),
        sa.Column('attack', sa.Integer(), nullable=True, default=1),
        sa.Column('defense', sa.Integer(), nullable=True, default=1),
        sa.Column('magic', sa.Integer(), nullable=True, default=1),
        sa.Column('difficulty', sa.Integer(), nullable=True, default=1),
        sa.Column('icon_url', sa.String(length=500), nullable=True),
        sa.Column('splash_url', sa.String(length=500), nullable=True),
        sa.Column('passive_icon_url', sa.String(length=500), nullable=True),
        sa.Column('spells', sa.Text(), nullable=True),
        sa.Column('passive', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('is_free_week', sa.Boolean(), nullable=True, default=False),
        sa.Column('version', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('champion_id'),
        sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('champions')
    # ### end Alembic commands ###
