"""baseline_from_existing_database

Revision ID: 1582e6e7d827
Revises: 14a2afb02d94
Create Date: 2025-09-15 19:28:51.762186+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1582e6e7d827"
down_revision: Union[str, None] = "14a2afb02d94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
