"""initial_migration_from_existing_database

Revision ID: 14a2afb02d94
Revises: 
Create Date: 2025-09-15 19:28:12.047422+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "14a2afb02d94"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "season_registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "WITHDRAWN",
                name="registrationstatus",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_user_id", sa.Integer(), nullable=True),
        sa.Column("review_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_season_registrations_id"), "season_registrations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_season_registrations_status"),
        "season_registrations",
        ["status"],
        unique=False,
    )
    op.create_table(
        "match_games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("game_number", sa.Integer(), nullable=False),
        sa.Column("team_a_score", sa.Integer(), nullable=True),
        sa.Column("team_b_score", sa.Integer(), nullable=True),
        sa.Column("winner_team_id", sa.Integer(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("riot_match_id", sa.String(length=100), nullable=True),
        sa.Column("game_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_match_games_id"), "match_games", ["id"], unique=False)
    op.create_index(
        op.f("ix_match_games_riot_match_id"),
        "match_games",
        ["riot_match_id"],
        unique=False,
    )
    op.alter_column(
        "match_check_ins",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("not_checked_in", "checked_in", name="checkinstatus"),
        existing_nullable=False,
    )
    op.drop_constraint(
        "match_check_ins_match_id_participant_id_key", "match_check_ins", type_="unique"
    )
    op.create_unique_constraint(
        "uq_match_participant_checkin",
        "match_check_ins",
        ["match_id", "participant_id"],
    )
    op.create_foreign_key(
        None, "match_check_ins", "tournament_matches", ["match_id"], ["id"]
    )
    op.add_column("matches", sa.Column("round_number", sa.Integer(), nullable=True))
    op.add_column("matches", sa.Column("match_number", sa.Integer(), nullable=True))
    op.add_column("matches", sa.Column("best_of", sa.Integer(), nullable=False))
    op.add_column("matches", sa.Column("notes", sa.Text(), nullable=True))
    op.alter_column("matches", "season_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "matches",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "SCHEDULED",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            "FORFEIT",
            name="matchstatus",
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'SCHEDULED'::character varying"),
    )
    op.alter_column(
        "matches",
        "result",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "TEAM_A_WIN", "TEAM_B_WIN", "DRAW", "CANCELLED", name="matchresult"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "scheduled_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "matches",
        "team_a_score",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "matches",
        "team_b_score",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index("ix_matches_season_id", table_name="matches")
    op.drop_index("ix_matches_team_a_id", table_name="matches")
    op.drop_index("ix_matches_team_b_id", table_name="matches")
    op.drop_index("ix_matches_tournament_id", table_name="matches")
    op.create_index(op.f("ix_matches_status"), "matches", ["status"], unique=False)
    op.drop_constraint("matches_tournament_id_fkey", "matches", type_="foreignkey")
    op.drop_constraint("matches_team_b_id_fkey", "matches", type_="foreignkey")
    op.drop_constraint("matches_team_a_id_fkey", "matches", type_="foreignkey")
    op.create_foreign_key(
        None, "matches", "teams", ["team_a_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "matches", "teams", ["team_b_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("matches", "tournament_id")
    op.add_column(
        "permissions", sa.Column("permission_id", sa.String(length=36), nullable=False)
    )
    op.add_column(
        "permissions",
        sa.Column("permission_name", sa.String(length=100), nullable=False),
    )
    op.drop_constraint("permissions_name_key", "permissions", type_="unique")
    op.drop_constraint("permissions_resource_action_key", "permissions", type_="unique")
    op.create_index(
        op.f("ix_permissions_permission_id"),
        "permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_permission_name"),
        "permissions",
        ["permission_name"],
        unique=True,
    )
    op.drop_column("permissions", "name")
    op.drop_column("permissions", "resource")
    op.drop_column("permissions", "id")
    op.drop_column("permissions", "action")
    op.alter_column(
        "player_profiles",
        "profile_id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "player_profiles",
        "summoner_name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint(
        "player_profiles_profile_id_key", "player_profiles", type_="unique"
    )
    op.drop_constraint(
        "player_profiles_current_team_id_fkey", "player_profiles", type_="foreignkey"
    )
    op.create_foreign_key(None, "player_profiles", "teams", ["current_team_id"], ["id"])
    op.drop_constraint("regions_name_key", "regions", type_="unique")
    op.add_column(
        "role_permissions",
        sa.Column("role_permission_id", sa.String(length=36), nullable=False),
    )
    op.add_column(
        "role_permissions",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "role_permissions",
        "permission_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.drop_constraint(
        "role_permissions_role_id_permission_id_key", "role_permissions", type_="unique"
    )
    op.create_index(
        op.f("ix_role_permissions_role_permission_id"),
        "role_permissions",
        ["role_permission_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_role_permission", "role_permissions", ["role_id", "permission_id"]
    )
    op.drop_constraint(
        "role_permissions_permission_id_fkey", "role_permissions", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "role_permissions",
        "permissions",
        ["permission_id"],
        ["permission_id"],
        ondelete="CASCADE",
    )
    op.drop_column("role_permissions", "id")
    op.drop_constraint("roles_name_key", "roles", type_="unique")
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.add_column(
        "seasons",
        sa.Column("registration_start_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "seasons",
        sa.Column("registration_end_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "seasons",
        sa.Column("season_start_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "seasons", sa.Column("season_end_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("seasons", sa.Column("min_teams", sa.Integer(), nullable=False))
    op.add_column(
        "seasons", sa.Column("auto_approve_registration", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "seasons", sa.Column("format_type", sa.String(length=50), nullable=False)
    )
    op.alter_column(
        "seasons",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "DRAFT",
            "REGISTRATION_OPEN",
            "REGISTRATION_CLOSED",
            "SCHEDULE_GENERATED",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            name="seasonstatus",
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'UPCOMING'::character varying"),
    )
    op.drop_index("ix_seasons_region_id", table_name="seasons")
    op.drop_constraint("seasons_name_region_id_key", "seasons", type_="unique")
    op.create_index(op.f("ix_seasons_name"), "seasons", ["name"], unique=False)
    op.create_index(op.f("ix_seasons_status"), "seasons", ["status"], unique=False)
    op.drop_column("seasons", "registration_deadline")
    op.drop_column("seasons", "end_date")
    op.drop_column("seasons", "start_date")
    op.add_column("team_members", sa.Column("user_id", sa.Integer(), nullable=False))
    op.alter_column(
        "team_members",
        "position",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'FILL'::character varying"),
    )
    op.drop_index("ix_team_members_player_profile_id", table_name="team_members")
    op.drop_index("ix_team_members_team_id", table_name="team_members")
    op.drop_constraint(
        "team_members_team_id_player_profile_id_key", "team_members", type_="unique"
    )
    op.create_unique_constraint(
        "uq_team_member", "team_members", ["team_id", "user_id"]
    )
    op.drop_constraint(
        "team_members_player_profile_id_fkey", "team_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "team_members", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("team_members", "is_captain")
    op.drop_column("team_members", "player_profile_id")
    op.add_column("teams", sa.Column("logo_url", sa.String(length=500), nullable=True))
    op.drop_index("ix_teams_captain_user_id", table_name="teams")
    op.drop_index("ix_teams_region_id", table_name="teams")
    op.drop_constraint("teams_name_region_id_key", "teams", type_="unique")
    op.drop_constraint("teams_tag_region_id_key", "teams", type_="unique")
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_unique_constraint("uq_team_region_name", "teams", ["region_id", "name"])
    op.create_unique_constraint("uq_team_region_tag", "teams", ["region_id", "tag"])
    op.drop_constraint("teams_captain_user_id_fkey", "teams", type_="foreignkey")
    op.create_foreign_key(
        None, "teams", "users", ["captain_user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("teams", "max_members")
    op.drop_column("teams", "min_rank_requirement")
    op.alter_column(
        "tournament_matches",
        "status",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum(
            "scheduled",
            "waiting_for_checkin",
            "checking_in",
            "ready",
            "in_progress",
            "completed",
            "cancelled",
            name="tournament_matchstatus",
        ),
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, "tournament_matches", "tournaments", ["tournament_id"], ["id"]
    )
    op.alter_column(
        "tournament_registrations",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "pending",
            "confirmed",
            "rejected",
            "withdrawn",
            name="tournament_registrationstatus",
        ),
        existing_nullable=False,
    )
    op.drop_constraint(
        "tournament_registrations_tournament_id_participant_id_key",
        "tournament_registrations",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_tournament_participant",
        "tournament_registrations",
        ["tournament_id", "participant_id"],
    )
    op.create_foreign_key(
        None, "tournament_registrations", "tournaments", ["tournament_id"], ["id"]
    )
    op.create_foreign_key(
        None, "tournament_registrations", "users", ["registered_by"], ["id"]
    )
    op.alter_column(
        "tournaments",
        "name",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.drop_index("ix_tournaments_created_by", table_name="tournaments")
    op.drop_index("ix_tournaments_region_id", table_name="tournaments")
    op.drop_index("ix_tournaments_status", table_name="tournaments")
    op.drop_constraint("tournaments_region_id_fkey", "tournaments", type_="foreignkey")
    op.create_foreign_key(None, "tournaments", "regions", ["region_id"], ["id"])
    op.drop_column("tournaments", "registration_count")
    op.drop_constraint(
        "user_roles_user_id_role_id_region_id_key", "user_roles", type_="unique"
    )
    op.create_index(op.f("ix_user_roles_id"), "user_roles", ["id"], unique=False)
    op.create_unique_constraint(
        "uq_user_role_region", "user_roles", ["user_id", "role_id", "region_id"]
    )
    op.drop_constraint(
        "user_roles_granted_by_user_id_fkey", "user_roles", type_="foreignkey"
    )
    op.create_foreign_key(None, "user_roles", "users", ["granted_by_user_id"], ["id"])
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.create_foreign_key(
        "user_roles_granted_by_user_id_fkey",
        "user_roles",
        "users",
        ["granted_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("uq_user_role_region", "user_roles", type_="unique")
    op.drop_index(op.f("ix_user_roles_id"), table_name="user_roles")
    op.create_unique_constraint(
        "user_roles_user_id_role_id_region_id_key",
        "user_roles",
        ["user_id", "role_id", "region_id"],
    )
    op.add_column(
        "tournaments",
        sa.Column(
            "registration_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "tournaments", type_="foreignkey")
    op.create_foreign_key(
        "tournaments_region_id_fkey",
        "tournaments",
        "regions",
        ["region_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_tournaments_status", "tournaments", ["status"], unique=False)
    op.create_index(
        "ix_tournaments_region_id", "tournaments", ["region_id"], unique=False
    )
    op.create_index(
        "ix_tournaments_created_by", "tournaments", ["created_by"], unique=False
    )
    op.alter_column(
        "tournaments",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.drop_constraint(None, "tournament_registrations", type_="foreignkey")
    op.drop_constraint(None, "tournament_registrations", type_="foreignkey")
    op.drop_constraint(
        "uq_tournament_participant", "tournament_registrations", type_="unique"
    )
    op.create_unique_constraint(
        "tournament_registrations_tournament_id_participant_id_key",
        "tournament_registrations",
        ["tournament_id", "participant_id"],
    )
    op.alter_column(
        "tournament_registrations",
        "status",
        existing_type=sa.Enum(
            "pending",
            "confirmed",
            "rejected",
            "withdrawn",
            name="tournament_registrationstatus",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_constraint(None, "tournament_matches", type_="foreignkey")
    op.alter_column(
        "tournament_matches",
        "status",
        existing_type=sa.Enum(
            "scheduled",
            "waiting_for_checkin",
            "checking_in",
            "ready",
            "in_progress",
            "completed",
            "cancelled",
            name="tournament_matchstatus",
        ),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.add_column(
        "teams",
        sa.Column(
            "min_rank_requirement",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "max_members",
            sa.INTEGER(),
            server_default=sa.text("5"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.create_foreign_key(
        "teams_captain_user_id_fkey", "teams", "users", ["captain_user_id"], ["id"]
    )
    op.drop_constraint("uq_team_region_tag", "teams", type_="unique")
    op.drop_constraint("uq_team_region_name", "teams", type_="unique")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.create_unique_constraint(
        "teams_tag_region_id_key", "teams", ["tag", "region_id"]
    )
    op.create_unique_constraint(
        "teams_name_region_id_key", "teams", ["name", "region_id"]
    )
    op.create_index("ix_teams_region_id", "teams", ["region_id"], unique=False)
    op.create_index(
        "ix_teams_captain_user_id", "teams", ["captain_user_id"], unique=False
    )
    op.drop_column("teams", "logo_url")
    op.add_column(
        "team_members",
        sa.Column(
            "player_profile_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "team_members",
        sa.Column(
            "is_captain",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "team_members", type_="foreignkey")
    op.create_foreign_key(
        "team_members_player_profile_id_fkey",
        "team_members",
        "player_profiles",
        ["player_profile_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_team_member", "team_members", type_="unique")
    op.create_unique_constraint(
        "team_members_team_id_player_profile_id_key",
        "team_members",
        ["team_id", "player_profile_id"],
    )
    op.create_index(
        "ix_team_members_team_id", "team_members", ["team_id"], unique=False
    )
    op.create_index(
        "ix_team_members_player_profile_id",
        "team_members",
        ["player_profile_id"],
        unique=False,
    )
    op.alter_column(
        "team_members",
        "position",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'FILL'::character varying"),
    )
    op.drop_column("team_members", "user_id")
    op.add_column(
        "seasons",
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "seasons", sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "seasons",
        sa.Column(
            "registration_deadline", sa.DATE(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_seasons_status"), table_name="seasons")
    op.drop_index(op.f("ix_seasons_name"), table_name="seasons")
    op.create_unique_constraint(
        "seasons_name_region_id_key", "seasons", ["name", "region_id"]
    )
    op.create_index("ix_seasons_region_id", "seasons", ["region_id"], unique=False)
    op.alter_column(
        "seasons",
        "status",
        existing_type=sa.Enum(
            "DRAFT",
            "REGISTRATION_OPEN",
            "REGISTRATION_CLOSED",
            "SCHEDULE_GENERATED",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            name="seasonstatus",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'UPCOMING'::character varying"),
    )
    op.drop_column("seasons", "format_type")
    op.drop_column("seasons", "auto_approve_registration")
    op.drop_column("seasons", "min_teams")
    op.drop_column("seasons", "season_end_at")
    op.drop_column("seasons", "season_start_at")
    op.drop_column("seasons", "registration_end_at")
    op.drop_column("seasons", "registration_start_at")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.create_unique_constraint("roles_name_key", "roles", ["name"])
    op.add_column(
        "role_permissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(None, "role_permissions", type_="foreignkey")
    op.create_foreign_key(
        "role_permissions_permission_id_fkey",
        "role_permissions",
        "permissions",
        ["permission_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_role_permission", "role_permissions", type_="unique")
    op.drop_index(
        op.f("ix_role_permissions_role_permission_id"), table_name="role_permissions"
    )
    op.create_unique_constraint(
        "role_permissions_role_id_permission_id_key",
        "role_permissions",
        ["role_id", "permission_id"],
    )
    op.alter_column(
        "role_permissions",
        "permission_id",
        existing_type=sa.String(length=36),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("role_permissions", "updated_at")
    op.drop_column("role_permissions", "role_permission_id")
    op.create_unique_constraint("regions_name_key", "regions", ["name"])
    op.drop_constraint(None, "player_profiles", type_="foreignkey")
    op.create_foreign_key(
        "player_profiles_current_team_id_fkey",
        "player_profiles",
        "teams",
        ["current_team_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_unique_constraint(
        "player_profiles_profile_id_key", "player_profiles", ["profile_id"]
    )
    op.alter_column(
        "player_profiles",
        "summoner_name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "player_profiles",
        "profile_id",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.add_column(
        "permissions",
        sa.Column("action", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.add_column(
        "permissions", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.add_column(
        "permissions",
        sa.Column(
            "resource", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "permissions",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_permissions_permission_name"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_permission_id"), table_name="permissions")
    op.create_unique_constraint(
        "permissions_resource_action_key", "permissions", ["resource", "action"]
    )
    op.create_unique_constraint("permissions_name_key", "permissions", ["name"])
    op.drop_column("permissions", "permission_name")
    op.drop_column("permissions", "permission_id")
    op.add_column(
        "matches",
        sa.Column("tournament_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "matches", type_="foreignkey")
    op.drop_constraint(None, "matches", type_="foreignkey")
    op.create_foreign_key(
        "matches_team_a_id_fkey", "matches", "teams", ["team_a_id"], ["id"]
    )
    op.create_foreign_key(
        "matches_team_b_id_fkey", "matches", "teams", ["team_b_id"], ["id"]
    )
    op.create_foreign_key(
        "matches_tournament_id_fkey",
        "matches",
        "tournaments",
        ["tournament_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_matches_status"), table_name="matches")
    op.create_index(
        "ix_matches_tournament_id", "matches", ["tournament_id"], unique=False
    )
    op.create_index("ix_matches_team_b_id", "matches", ["team_b_id"], unique=False)
    op.create_index("ix_matches_team_a_id", "matches", ["team_a_id"], unique=False)
    op.create_index("ix_matches_season_id", "matches", ["season_id"], unique=False)
    op.alter_column(
        "matches",
        "team_b_score",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "matches",
        "team_a_score",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "matches",
        "scheduled_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "matches",
        "result",
        existing_type=sa.Enum(
            "TEAM_A_WIN", "TEAM_B_WIN", "DRAW", "CANCELLED", name="matchresult"
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "matches",
        "status",
        existing_type=sa.Enum(
            "SCHEDULED",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED",
            "FORFEIT",
            name="matchstatus",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'SCHEDULED'::character varying"),
    )
    op.alter_column("matches", "season_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("matches", "notes")
    op.drop_column("matches", "best_of")
    op.drop_column("matches", "match_number")
    op.drop_column("matches", "round_number")
    op.drop_constraint(None, "match_check_ins", type_="foreignkey")
    op.drop_constraint(
        "uq_match_participant_checkin", "match_check_ins", type_="unique"
    )
    op.create_unique_constraint(
        "match_check_ins_match_id_participant_id_key",
        "match_check_ins",
        ["match_id", "participant_id"],
    )
    op.alter_column(
        "match_check_ins",
        "status",
        existing_type=sa.Enum("not_checked_in", "checked_in", name="checkinstatus"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_match_games_riot_match_id"), table_name="match_games")
    op.drop_index(op.f("ix_match_games_id"), table_name="match_games")
    op.drop_table("match_games")
    op.drop_index(
        op.f("ix_season_registrations_status"), table_name="season_registrations"
    )
    op.drop_index(op.f("ix_season_registrations_id"), table_name="season_registrations")
    op.drop_table("season_registrations")
    # ### end Alembic commands ###
