"""fix_tournament_registrations_timezone_only

Revision ID: d0f85890404c
Revises: c1fba4716591
Create Date: 2025-09-18 03:41:03.174440+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f85890404c'
down_revision: Union[str, None] = 'c1fba4716591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix timezone issue for tournament_registrations.registered_at field
    op.alter_column('tournament_registrations', 'registered_at',
                   existing_type=sa.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert timezone fix for tournament_registrations.registered_at field
    op.alter_column('tournament_registrations', 'registered_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=sa.TIMESTAMP(),
                   existing_nullable=False)
    # ### end Alembic commands ###
