"""add_bp_core_dictionary_tables

Revision ID: 68caff20a234
Revises: bc837fb65afe
Create Date: 2025-09-17 07:39:25.436564+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68caff20a234'
down_revision: Union[str, None] = 'bc837fb65afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create BP Actions dictionary table
    op.create_table('dict_bp_actions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('display_name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create BP Teams dictionary table
    op.create_table('dict_bp_teams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('display_name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create BP Phases dictionary table
    op.create_table('dict_bp_phases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('display_name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create BP Session Statuses dictionary table
    op.create_table('dict_bp_session_statuses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('display_name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Insert initial data for BP Actions
    op.execute("""
        INSERT INTO dict_bp_actions (code, name, display_name, description, sort_order) VALUES
        ('ban', 'Ban', '禁用', 'BP阶段的英雄禁用操作', 1),
        ('pick', 'Pick', '选择', 'BP阶段的英雄选择操作', 2)
    """)
    
    # Insert initial data for BP Teams  
    op.execute("""
        INSERT INTO dict_bp_teams (code, name, display_name, description, sort_order) VALUES
        ('blue', 'Blue', '蓝方', 'BP蓝方队伍', 1),
        ('red', 'Red', '红方', 'BP红方队伍', 2)
    """)
    
    # Insert initial data for BP Phases
    op.execute("""
        INSERT INTO dict_bp_phases (code, name, display_name, description, sort_order) VALUES
        ('waiting', 'Waiting', '等待开始', '等待BP开始', 1),
        ('ban_phase_1', 'Ban Phase 1', '第一轮禁用', '第一轮英雄禁用阶段', 2),
        ('pick_phase_1', 'Pick Phase 1', '第一轮选择', '第一轮英雄选择阶段', 3),
        ('ban_phase_2', 'Ban Phase 2', '第二轮禁用', '第二轮英雄禁用阶段', 4),
        ('pick_phase_2', 'Pick Phase 2', '第二轮选择', '第二轮英雄选择阶段', 5),
        ('completed', 'Completed', 'BP完成', 'BP流程已完成', 6),
        ('cancelled', 'Cancelled', 'BP取消', 'BP流程已取消', 7)
    """)
    
    # Insert initial data for BP Session Statuses
    op.execute("""
        INSERT INTO dict_bp_session_statuses (code, name, display_name, description, sort_order) VALUES
        ('inactive', 'Inactive', '未激活', 'BP会话未激活状态', 1),
        ('active', 'Active', '进行中', 'BP会话进行中状态', 2),
        ('paused', 'Paused', '暂停', 'BP会话暂停状态', 3),
        ('completed', 'Completed', '已完成', 'BP会话已完成状态', 4),
        ('cancelled', 'Cancelled', '已取消', 'BP会话已取消状态', 5)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop BP dictionary tables
    op.drop_table('dict_bp_session_statuses')
    op.drop_table('dict_bp_phases')
    op.drop_table('dict_bp_teams')
    op.drop_table('dict_bp_actions')
    # ### end Alembic commands ###
